### PR TITLE
Function call highlighting, multiple bug fixes, and more

### PR DESCRIPTION
**Pull request by farzher**
I don't blame you for not accepting this pull request, my commits are insane. BUT, I have a lot of good stuff here (plus multiple bugfixes), so at least you can see all of my code and take what you'd like.

Here's some demo code using current LiveScript.tmbundle
before

Same code after applying my edits
after

### CODE REVIEW

**Comment by vendethiel** [comment]
I totally forgot about this - can this be merged as-is, or are there outstanding issues?

**Comment by farzher** [comment]
I don't think so. I'm still using these exact changes with no more additions.

It looks like this was mentioned a few times as a fix. I don't see any complaints.

**Comment by vendethiel** [comment]
Great then -- terribly sorry for such a delay.

Thanks again! :star:

@paulmillr mind adding a contributor? Thanks!

**Comment by paulmillr** [comment]
Added.

**Comment by paulmillr** [comment]
Brilliant work, btw.

**Pull request merged**
